# Generated by Django 3.2.10 on 2021-12-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('CHF', 'CHF'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=3)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('date', models.DateField()),
                ('frequency', models.CharField(choices=[('monthly', 'monthly'), ('half-yearly', 'half-yearly'), ('yearly', 'yearly'), ('single', 'single')], max_length=11)),
                ('status', models.CharField(choices=[('open', 'open'), ('overdue', 'overdue'), ('aborted', 'aborted'), ('paid', 'paid')], max_length=7)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
